diff error at least
idk why i think this will work
OpenQA.Selenium.DriverServiceNotFoundException: The file ./chromedriver does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html